[build]
  publish = "."
  command = "echo 'No build command needed for static files.'"

[[redirects]]
  from = "/bot"
  to = "/bot-og.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

